SERVER_SOURCE=server/*.cpp
SERVER_OUTPUT=server/output/server
SERVER_LIBRARIES=

CLIENT_SOURCE=client/*.cpp
CLIENT_OUTPUT=client/output/client
CLIENT_LIBRARIES=pthread

CXX=g++
CXXFLAGS=-Wall -ansi -pedantic

all: $(SERVER_OUTPUT) $(CLIENT_OUTPUT)

$(SERVER_OUTPUT): $(SERVER_SOURCE)
	$(CXX) $(CXXFLAGS) $(SERVER_SOURCE) -o$(SERVER_OUTPUT)

$(CLIENT_OUTPUT): $(CLIENT_SOURCE)
	$(CXX) $(CXXFLAGS) $(CLIENT_SOURCE) -o$(CLIENT_OUTPUT) -l$(CLIENT_LIBRARIES)

clean:
	rm -f $(SERVER_OUTPUT)
	rm -f $(CLIENT_OUTPUT)
