MKDIR_P=mkdir -p

SERVER_SOURCE=server/*.cpp
SERVER_OUTPUT_DIR=server/output
SERVER_OUTPUT=$(SERVER_OUTPUT_DIR)/messenger_server
SERVER_LIBRARIES=

CLIENT_SOURCE=client/*.cpp
CLIENT_OUTPUT_DIR=client/output
CLIENT_OUTPUT=$(CLIENT_OUTPUT_DIR)/messenger_client
CLIENT_LIBRARIES=pthread

CXX=g++
CXXFLAGS=-Wall -ansi -pedantic

all: $(SERVER_OUTPUT) $(CLIENT_OUTPUT)

$(SERVER_OUTPUT): $(SERVER_SOURCE)
	$(MKDIR_P) $(SERVER_OUTPUT_DIR)
	$(CXX) $(CXXFLAGS) -std=c++11 $(SERVER_SOURCE) -o$(SERVER_OUTPUT)

$(CLIENT_OUTPUT): $(CLIENT_SOURCE)
	$(MKDIR_P) $(CLIENT_OUTPUT_DIR)
	$(CXX) $(CXXFLAGS) -std=c++11 $(CLIENT_SOURCE) -o$(CLIENT_OUTPUT) -l$(CLIENT_LIBRARIES)

clean:
	rm -f $(SERVER_OUTPUT)
	rm -f $(CLIENT_OUTPUT)
